import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Layout from '@/components/Layout.tsx'
import NameCard from '@/components/NameCard.tsx'
import SectionHeading from '@/components/SectionHeading'

const inter = Inter({ subsets: ['latin'] })

const Intro = () => {
  return (
    <>
          <p>
              I am a PhD candidate at <Link href="https://ttic.edu/">TTIC</Link>
              , an academic institute located on the campus of the <Link href="https://www.uchicago.edu/">University of Chicago</Link>.
              My research interest lies in the intersection of Reinforcement Learning and Natural Language Processing, especially in the context of robotics.
          </p>
          <p>
              In the past, I have interned at several places including <Link href="https://mr.cs.ucl.ac.uk/">UCL</Link>(2018 summer) and <Link href="https://www.preferred.jp/en/">Preferred Networks</Link> (2019 summer)
              which is known for <Link href="https://github.com/chainer/chainer">Chainer</Link>.
              I am now at <Link href="https://ttic.edu/ripl/">Robot Intelligence through Perception Lab</Link>{' '}
              working with <Link href="https://bstadie.github.io/">Bradly Stadie</Link> and <Link href="https://ttic.uchicago.edu/~mwalter/">Matthew R. Walter</Link>.
              <br />
          </p>
      <p className='mt-2'>
        TTIC featured me recently: <Link href="https://www.ttic.edu/student-highlights/yoneda/">Takuma Yoneda - Student Highlight</Link>
      </p>
    </>
  )
}


const Publications = () => {
  return (
    <>
      <SectionHeading>Publications (<Link href='https://scholar.google.com/citations?user=EtYv_AIAAAAJ&hl=en'>Google Scholar</Link>)</SectionHeading>
      <ul className='list-disc list-inside'>
        <li>foo</li>
        <li>bar</li>
      </ul>
    </>
  )
}

const Internships = () => {
  return (
    <>
      <SectionHeading>Internships</SectionHeading>
      <p>internships</p>
    </>
  )
}

const Talks = () => {
  return (
    <>
      <SectionHeading>Talks</SectionHeading>
      <p>talks</p>
    </>
  )
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Takuma Yoneda</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main>
          <NameCard
            name="Takuma Yoneda"
            image_url="/tyoneda.jpg"
            mobile={false}
          />
          <div className='flex flex-col items-center'>
            <div className='max-w-screen-md'>
              <Intro />
              <Publications />
              <Internships />
              <Talks />
            </div>
          </div>
        </main>
      </Layout>
    </>
  )
}
